export const ROLES = {
    ADMINISTRADOR: '[COORDINADOR INFORMATICO]',
    ASISTENTE_INFORMATICO: '[ASISTENTE INFORMATICO]',
    SOPORTE_TECNICO: '[SOPORTE TECNICO]',
    USUARIO_COMUN: '[USUARIO COMUN]',
}