export const types = {

    login: '[Auth] Login',
    logout: '[Auth] Logout',
    authCheckingFinish: '[Auth] Finish checking login state',

    eventLoadedPerfil: '[event] Events loaded Perfil',
    eventLoadedPersona: '[event] Events loaded Persona',
    eventLoadedSede: '[event] Events loaded Sedes',
    eventLoadedOrgano: '[event] Events loaded Organos',
    eventLoadedOficina: '[event] Events loaded Oficinas',
    eventLoadedCargo: '[event] Events loaded Cargos',
    eventLoadedUsuarioValidadorDni: '[event] Events loaded UsuarioValidadorDni',
    eventOrganoId: '[event] OrganoId',
    eventLoadedMisIncidencias: '[event] Events loaded Mis Incidencias',
    eventLoadedIncidencia: '[event] Events loaded Incidencia',
    eventLoadedIncidenciaId: '[event] Events loaded IncidenciaId',
    eventLoadedIncidenciasAsignadas: '[event] Events loaded Incidencias Asignadas',
    eventLoadedIncidenciasNoAsignadas: '[event] Events loaded Incidencias No Asignadas',
    eventLoadedIncidenciasAsignadasSoporte: '[event] Events loaded Incidencias Asignadas a Soporte',
    eventLoadedTecnicoDisponible: '[event] Events loaded Tecnicos Disponibles',
    eventLoadedMotivo: '[event] Events loaded Motivo',
    eventLoadedPersonaOrgano: '[event] Events loaded PersonaOrgano',
    eventLoadedCorreoRecibido: '[event] Events loaded Correo Recibido',
    eventLoadedCorreoEnviado: '[event] Events loaded Correo Enviado',
    eventLoadedOrigenIncidencia: '[event] Events loaded Origen Incidencia',
    eventLoadedFtp: '[event] Events loaded Ftp',
    eventLoadedCorreoCredencial: '[event] Events loaded Correo Credencial',
    eventLoadedConfigurarBotones : '[event] Events loaded Configurar Botones',
    eventLoadedMensajes: '[event] Events loaded Mensajes',
}